#version: "3.9"
services:
  
  # Zookeeper per Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


  # Microservizio Segnalazione Utenti 
  segnalazione_utenti:
    build:
      context: ./Segnalazione Utenti
      dockerfile: Dockerfile
    container_name: segnalazione-utenti
    command: python3 segnalazioneUtenti.py
    depends_on:
      - kafka
    ports:
      - "5006:5006"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092



  # Microservizio Analisi Dati
  analisi_dati:
    build: 
      context: ./Analisi Dati
      dockerfile: Dockerfile
    container_name: analisi-dati
    command: python3 appAnalisi.py
    ports:
      - "5001:5001"
    depends_on:
      - kafka


  # Microservizio Raccolta Dati
  raccolta_dati:
    build: 
      context: ./Raccolta Dati
      dockerfile: Dockerfile
    container_name: raccolta-dati
    command: python3 appRaccolta.py
    environment:
      - ANALISI_URL=http://analisi-dati:5001/analizza
    ports:
      - "5005:5005"
    depends_on:
    - analisi_dati

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  gestionepreferiti:
    build: ./GestionePreferiti  
    container_name: gestionePreferiti
    depends_on:
      - dynamodb  
      - gestioneutente
    environment:  
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      AWS_REGION: "us-east-1"
    ports:
      - "5004:5004"


  gestioneutente:
    build: ./gestioneutente
    container_name: gestioneutente
    depends_on:
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Users"
    ports:
     - "5002:5001" 

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - gestioneutente
      - gestionepreferiti
      - kafka
      - notifica
    stdin_open: true
    tty: true
    ports:
      - "3000:3000" 


  init-topics:
    build: ./InizializzazioneTopic
    container_name: init-topics
    command: python3 init_topics.py
    depends_on:
      - kafka
    volumes:
      - ./InizializzazioneTopic/fiumi_sottobacini.json:/app/fiumi_sottobacini.json

  notifica:
    build:
      context: ./Notifica
    container_name: notifica
    depends_on:
      - kafka
      - gestioneutente
      - gestionepreferiti
    environment:
      PREFERITI_URL: "http://gestionePreferiti:5004/controllo_preferiti"
    ports:
      - "5006:5006"




